---
title: "Data Wrangling"
---

> Data wrangling is the process of transforming and mapping data from one "raw" data form 
> into another format with the intent of making it more appropriate and valuable for a 
> variety of downstream purposes such as analytics.
>
> -- [_Wikipedia_](https://en.wikipedia.org/wiki/Data_wrangling)


## Tidy Data

The Tidyverse of packages are built around the concept of tidy data, first introduced by 
Jeff Leek in his book _The Elements of Data Analytic Style_. Hadley Wickham summarises the 
characteristics of [tidy data](http://tidyr.tidyverse.org/articles/tidy-data.html) with 
the following points:

 1. Each variable forms a column.
 2. Each observation forms a row.
 3. Each type of observational unit forms a table.


## Cheatsheets

RStudio provide a selection of cheatsheets containing quick reference of R functions 
useful for common task:

```{r, echo=FALSE}
thumbnail(
  "Data Import", 
  "images/data-import-cheatsheet-1.png",
  "https://github.com/rstudio/cheatsheets/raw/master/data-import.pdf")

thumbnail(
  "Data Transformation", 
  "images/data-transformation-cheatsheet.png",
  "https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf")

thumbnail(
  "Strings", 
  "images/strings.png",
  "https://github.com/rstudio/cheatsheets/raw/master/strings.pdf")

thumbnail(
  "Dates and Times", 
  "images/lubridate.png",
  "https://github.com/rstudio/cheatsheets/raw/master/lubridate.pdf")
```


## Importing Data

The first step in wrangling is importing the data into R. The methods to do so depend on the 
source of data:

 - Reading files
 - Connecting to databases
 - Web APIs or pages


#### Reading Files

Files may come in many formats and R has packages to read many of them. The most common 
for data science are tabular text files, such as CSVs, and Excel spreadsheets. The 
recommended packages for reading these files are:.

 - [`readr`](http://readr.tidyverse.org/) for reading text files
 - [`readxl`](http://readxl.tidyverse.org/) for reading Excel files
 - [`openxlsx`](https://www.rdocumentation.org/packages/openxlsx/) for writing to Excel 
   files


#### Connecting to Databases

The new [RStudio Connections Pane](https://db.rstudio.com/) makes it possible to easily
connect to a variety of data sources, and explore the objects and data inside the 
connection.

The recommended packages for connecting to databases (also used by RStudio) are:

 - [`DBI`](https://db.rstudio.com/DBI) provides a standard interface to any database
 - [`odbc`](https://db.rstudio.com/odbc/) for connecting to databases using ODBC
 - [`dplyr`](https://db.rstudio.com/dplyr/) for transforming tables in a database


#### Web APIs and Pages

Obtaining data from the internet has two main approaches. If the website provides an
application programming interface (API) then you can send and receive data through it.
The data from web APIs is usually returned in JSON or XML format. Alternatively, you can
scrape the website itself, extracting data from the pages. The recommended packages for 
these approaches are:

 - [`httr`](http://httr.r-lib.org/) for communicating with web APIs
 - [`jsonlite`](https://www.rdocumentation.org/packages/jsonlite) for reading JSON 
   formatted text
 - [`xml2`](https://www.rdocumentation.org/packages/xml2) for reading XML formatted text
 - [`rvest`](https://www.rdocumentation.org/packages/rvest) for scraping 
   web pages


## Tidying Data

Now you have the data you want, it probably requires some processing in order to get it
into a structure that is useful for analysis. There are two main packages for this 
[`tidyr`](http://tidyr.tidyverse.org) and [`dplyr`](http://dplyr.tidyverse.org):


#### [`tidyr`](http://tidyr.tidyverse.org)

The focus of [`tidyr`](http://tidyr.tidyverse.org) is to get the data into a tidy format. 
The main functions it provides to do this are:

 - [`gather()`](http://tidyr.tidyverse.org/reference/gather.html) takes multiple columns, 
   and gathers them into key-value pairs: it makes "wide" data longer.
 - [`spread()`](http://tidyr.tidyverse.org/reference/spread.html) takes two columns (key 
   & value) and spreads in to multiple columns, it makes "long" data wider.
 - [`separate()`](http://tidyr.tidyverse.org/reference/separate.html) and 
   [`extract()`](http://tidyr.tidyverse.org/reference/extract.html) pulls apart a column 
   that represents multiple variables.
 - [`unite()`](http://tidyr.tidyverse.org/reference/unite.html) combines columns, useful 
   if one is redundant.
 - [`separate_rows()`](http://tidyr.tidyverse.org/reference/gather.html) for separating 
   a row that contains multiple observations.

In addition, [`tidyr`](http://tidyr.tidyverse.org) provides a set of functions for dealing
with implicit and explicit missing values:

 - [`drop_na()`](http://tidyr.tidyverse.org/reference/drop_na.html): Drop rows containing
   missing values
 - [`replace_na()`](http://tidyr.tidyverse.org/reference/replace_na.html): Replace missing
   values
 - [`fill()`](http://tidyr.tidyverse.org/reference/fill.html): Fill in missing values.
 - [`complete()`](http://tidyr.tidyverse.org/reference/complete.html): Complete a data frame
   with missing combinations of data.
 - [`expand()`](http://tidyr.tidyverse.org/reference/expand.html), 
   [`crossing()`](http://tidyr.tidyverse.org/reference/expand.html): Expand data frame to
   include all combinations of values


#### [`dplyr`](http://dplyr.tidyverse.org)

[`dplyr`](http://dplyr.tidyverse.org) is a grammar of data manipulation, providing a
consistent set of verbs that help you solve the most common data manipulation challenges:

 - [`mutate()`](http://dplyr.tidyverse.org/reference/mutate.html) adds new variables that 
   are functions of existing variables.
 - [`select()`](http://dplyr.tidyverse.org/reference/select.html) picks variables based on
   their names.
 - [`filter()`](http://dplyr.tidyverse.org/reference/filter.html) picks cases based on 
   their values.
 - [`summarise()`](http://dplyr.tidyverse.org/reference/summarise.html) reduces multiple 
   values down to a single summary.
 - [`arrange()`](http://dplyr.tidyverse.org/reference/arrange.html) changes the ordering of 
   the rows.

These all combine naturally with
[`group_by()`](http://dplyr.tidyverse.org/reference/group_by.html) which allows you to 
perform any operation "by group".

[`dplyr`](http://dplyr.tidyverse.org) also provides a set of functions for combining 
tables. Mutating joins combine tables based on matching a subset of common variables; 
Set operations expect the tables to have the same variables and combine observations like
sets.

**Mutating joins**

 - [`inner_join(x, y)`](http://dplyr.tidyverse.org/reference/join.html) only includes
   observations that match in both `x` and `y`.
 - [`left_join(x, y)`](http://dplyr.tidyverse.org/reference/join.html) includes all
   observations in `x`, regardless of whether they match or not.
 - [`right_join(x, y)`](http://dplyr.tidyverse.org/reference/join.html) includes all
   observations in `y`. It’s equivalent to 
   [`left_join(y, x)`](http://dplyr.tidyverse.org/reference/join.html), but the columns 
   will be ordered differently.
 - [`full_join()`](http://dplyr.tidyverse.org/reference/join.html) includes all 
   observations from `x` and `y`.

**Set operations**

 - [`intersect(x, y)`](http://dplyr.tidyverse.org/reference/setops.html): returns only
   observations in both `x` and `y`.
 - [`union(x, y)`](http://dplyr.tidyverse.org/reference/setops.html): returns unique
   observations in `x` and `y`.
 - [`setdiff(x, y)`](http://dplyr.tidyverse.org/reference/setops.html): return observations 
   in `x`, but not in `y`.


#### Variable Types

There are also packages which simplify working with specific types of data:

 - [`stringr`](http://stringr.tidyverse.org/) for strings and regular expressions
 - [`forcats`](http://forcats.tidyverse.org/) for factors, used to handle categorical data
 - [`lubridate`](http://lubridate.tidyverse.org/) for dates and date-times.
 - [`hms`](https://www.rdocumentation.org/packages/hms) for time-of-day values.


#### [`tibble`](http://tibble.tidyverse.org/)

When using these packages you may notice they return a `tibble` rather than a `data.frame`.
They are basically the same thing with three key differences:

 1. Printing: Tibbles only show the first ten rows and all the columns that fit on one 
    screen.
 2. Subsetting: `[` always returns another tibble. `$` never uses partial matching.
 3. Recycling: Only values of length 1 are recycled. Trying to combine columns of 
    different length throws an error.

The package [`tibble`](http://tibble.tidyverse.org/) has some useful functions for
constructing tibbles. In particaular, you can construct a tibble row-wise using the
[`tribble`](http://tibble.tidyverse.org/reference/tribble.html) function (transposed 
tibble).
