---
title: "Structure"
---

Organising files for a particular piece of work becomes more important as the scale and 
complexity increases. Standard approaches exists to simplify the workflow.


## Projects

Use RStudio projects to organise files. This has a number of advantages:

1. Sets the working directory to the project location
1. Reopens the same files when returning to the projects


## Folders

When an analysis becomes complex it should be split up into logical parts and stored in 
subfolders. Store the original data in a folder, unchanged. It is better to "cleanse" input
data with an R script as it can repeated when data changes, and/or the approach changed 
itself.

R code may also be stored in a separate folder. You may have an R script for cleansing the 
data and another for performing an analysis. Include an R script at the top level which 
executes the code in the subfolder in the appropriate order. Use relative paths to the 
files. If an RStudio project has been created the working directory will be set to the 
project directory automatically.

Output the results, plots, data, etc, in another folder so it is clear whether data files 
are results rather than inputs.

An example of a project structure:

 - data
    - interesting_data.xlsx
    - reference_data.csv
 - R
    - clean_data.R
    - analyse.R
 - tests
    - test_cleansed_data.R
    - test_analysis.R
 - results
    - cool_plot.png
    - table_of_results.csv
 - run_code.R 
 - README.md


## README

Adding a README file is a good way to explain to other, and you future self, what the analysis
does and how to use it. The [documentation](index.html#documentation) section of the best 
practice has more detail on what should be included.

It is recommended that [markdown](http://rmarkdown.rstudio.com/lesson-8.html) is used to 
write the README. It is a very simple way to specify text formatting in a plain text file
and can be converted to many other formats (HTML, docx, PDF) if required. In addition, if 
the package is stored in GitHub a markdown README is automatically rendered on the 
repository's page.


## R Packages

When R code has high criticality consider turning it into a package. A package is a way 
of collecting together related code in a robust way. It has the following advantages:

 - Easier to share with others (as a zip file)
 - Documentation is compiled into help pages
 - All tests can be executed with a single command
 - Can implement a development and release process
 - Code is broken up into useful functions

Writing a package is very straight forward with the helper packages available today. More
information can be found in [Package Development](packages-development.html).
